apiVersion: v1
kind : Service
metadata:
    name: cls515-labmaven-eq19
    namespace: eq19
spec:
  type: NodePort
  selector:
    app: cls515-labmaven-eq19
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001