apiVersion: apps/v1
kind: Deployment
metadata:
  name: cls515-labmaven-eq19
  namespace: eq19
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cls515-labmaven-eq19
  template:
    metadata:
      labels:
        app: cls515-labmaven-eq19
    spec:
      containers:
        - name: cls515-labmaven-eq19
          image: 10.10.0.30:8081/edu.mv/cls515-labmaven-eq19:1
          ports:
            - containerPort: 8081
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
