apiVersion: v1
kind : Service
metadata:
  name: cls515-labmaven-eq19
  namespace: eq19
spec:
  type: NodePort
  selector:
    app: cls515-labmaven-eq19
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30001