apiVersion: v1
kind : Service
metadata:
  name: cls515-labmaven-eq199
  namespace: eq199
spec:
  type: NodePort
  selector:
    app: cls515-labmaven-eq199
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001